### PR TITLE
Disable form controls on xx-events until ready

### PR DESCRIPTION
**Pull request by WebReflection**
This MR addresses `py-click` or any other polyscript handled event so that form controls won't be usable until the interpreter is actually bootstrapped, avoiding possible errors if the user performs an action for something not bootstrapped yet.

### CODE REVIEW

**Review by ntoll — APPROVED** [review]
Nice one. :shipit: 

I like how you're using MicroPython to test it too!

**Comment by JeffersGlass** [comment]
This might be overkill, but is it worth adding the ability distinguish between elements disabled by PyScript and those disabled otherwise? I'm thinking of:

```html
<label for="name">CC Number:</label>
<input name="name" type="text"  disabled/>

<label for="terms">I've read the terms and conditions</label>
<input type="checkbox" id="terms" name="terms" value="yes" py-change="processTC">
```

If I'm understanding right, there would be no way to query for inputs disabled by Polyscript and those disabled by other means while Polyscript is loading, since both are just `disabled`, yes? Maybe the ones disabled by polyscript get a `poly-disabled` attribute or something?

May be overthinking this, I know hypotheticals aren't always helpful.

**Comment by WebReflection** [comment]
> there would be no way to query for inputs disabled by Polyscript and those disabled by other means while Polyscript is loading

any prefixed event hints there was a type (interpreter) or custom type (py / mpy) to wait for ... the disabled state is not touched if elements are already disabled (it's a user intent, we don't do anything in there) and any other form that doesn't have well known prefixed events is also untouched ... + the disable disappears pretty soon so checking the state is really not useful but CSS would work wonderfully if you target `input[py-click]:disabled {}` as example ... I think we're good, without compromising the logic or making it more complex for unclear use cases.

**Comment by WebReflection** [comment]
@JeffersGlass if that's OK, we can revisit this after users' feedback in case your case is really desired, I hope that works!

**Comment by JeffersGlass** [comment]
Of course! No worries @WebReflection, we can visit it again if anyone actually asks for that feature. 👍

**Pull request merged**
