### PR TITLE
[blocked] Pyodide v0.24.0 - will be 0.24.1

### PR DESCRIPTION
**Pull request by WebReflection**
This MR would like to update Pyodide to its latest version:
https://blog.pyodide.org/posts/0.24-release/

Everything works just fine but I haven't brought in any new feature ... however, what I've observed by local tests:

  * there's no visible/relevant bootstrap speedup
  * if I pass packages as array directly to `loadPyodide` (avoiding the manual dance) matplot example breaks and fail due pyodide bootstrap errors ... ~~I haven't fully read the API change or feature so this might be on me - **update** opened an issue in pyodide https://github.com/pyodide/pyodide/issues/4152~~ **update** this is indeed *matplotlib* breaking with latst Pyodide
  * I haven't tried other things like the filename as that requires bigger changes/refactoring so I agree with @antocuni we might want to add/check that *after* our RC1 goes out

If there's any other fix we'd like to have, this MR is ready to go AS-IS and I've seen no regression whatsoever so it's probably worth it updating before the RC goes out.

### CODE REVIEW

**Comment by WebReflection** [comment]
### WARNING

The *matplotlib* package breaks with Pyodide 0.24.0 (other packages seem to be fine) ... I'd like to put this change **on hold** until we have time to actually check everything is fine.

**Comment by bugzpodder** [comment]
i ran into a similar issue for matplotlib on worker only, but may be running on 0.24.0.  I will double check this.

**Comment by WebReflection** [comment]
FYI it looks like our matplotlib examples are all broken due https://github.com/pyodide/pyodide/issues/4153#issuecomment-1724879825 ... I will try to fix that in here and see how it goes but honestly I am not sure how to fix that as I don't know the lib much. Any help appreciated /cc @antocuni @JeffersGlass

**Comment by WebReflection** [comment]
Confirmed the **blocker** for this Pyodide release https://github.com/pyodide/pyodide/issues/4153#issuecomment-1725125095

We probably need to wait for the next one and be sure our examples still work.

**Comment by WebReflection** [comment]
I am updating both Pyodide and Ruby in this follow up MR https://github.com/pyscript/polyscript/pull/49

Closing this as behind current main and not Ruby related too.

**Pull request closed without merging**
