### PR TITLE
Allow embedders to avoid default interpreters

### PR DESCRIPTION
**Pull request by WebReflection**
Coming from this comment https://github.com/pyscript/pyscript/pull/1728#issuecomment-1729516673 I *think* there is a desire to have default *polyscript* behavior out of our way.

This MR makes it possible for embedders to actually reach *polyscript* internals and nullify the default dance for all core interpreters and types such as `pyodide`, `micropython`, `wasmoon` or `ruby-wasm-wasi`, so that running both *PyScript* and *polyscript* in the same page actually won't conflict with each/other intents, whenever that's explicitly desired, but most importantly this exclude any "*we should throw on `<script type="...">` for reasons*", as we can't throw on any custom `<script type="...">` possibly available in the wild and we also shouldn't, as that's the core feature that enabled both *polyscript* and *PyScript* projects, so this is an attempt to allow us to fully ignore core interpreters without being ever obtrusive or hostile for the rest of the world.

/cc @antocuni

### CODE REVIEW

**Comment by WebReflection** [comment]
To dig into details, we already reach *polyscript* module internals and we can now `import` both `selectors` and `prefixes` before registering our own custom types, nullifying by all means the parsing of core interpreters by simply `selectors.splice(0)` and `prefixes.splice(0)` operations.

This will not throw on otherwise fully valid `type` scripts, it sill simply ignore these as never executed/processed, unless the *polyscript* module itself is also embedded, without clashing among the two.

We should never throw on `<script type="...">` as that would both create a bad precedent ... but if anyone is really keen to do so, we should do that elsewhere, not here, as throwing on script types is not a responsibility of this module.

**Review by antocuni — APPROVED** [review]
I don't have any knowledge of the polyscript internals and I have no idea of what this PR is doing 😅.
If I understand correctly, it will allow pyscript to disable "other" interpreters, if we want?

**Comment by antocuni** [comment]
> example ... a <script type="micropython"> is on the page, we have a hints plugin that spot it and says: "have you tried <script type="mpy"> instead? See PyScript project to know more" ... or anything along these lines.

got it! Works for me!

**Comment by ntoll** [comment]
@WebReflection this definitely is a step forward. So, if someone puts `<script type="micropython">` they get a warning they should use `mpy` instead... or we just use PyScript's version of Micropython (whatever behaviour we prefer - or both)..? That feels like a kinder thing to do for the users, rather than bring attention to Polyscript... they should know it exists, but that's all they should know.

**Comment by WebReflection** [comment]
@ntoll to clarify:

  * this MR simply exposes a way for embedders to get rid core interpreters
  * by default, this MR does nothing different but it allows *PyScript* to avoid interfering with unhandled types
  * once this gets in, we *could* add on top more guidance or hints about those types
  * once we disable those types, an explicit *polyscript* module on the same page would still work

In short, there's more work to do on *PyScript* side once this is in in *polyscript*, but all ways to gracefully do what we want is there, except mixing `type="micropython"` as that might result into racing MutationObserver dance if the foreign *polyscript* is added explicitly by a user, because both libraries would then try to handle those nodes.

If this is clear and there are no other questions, I'd be happy to move forward with this PR, thanks.

**Comment by ntoll** [comment]
@WebReflection thank you for clearing up the situation. :shipit: :+1:

**Comment by WebReflection** [comment]
OK folks, I am going ahead with this as I think it's needed to also fix an issue with hooks added on module import and that could be too late when `worker` attributes are around ... I've tested this and I am happy too with the results so ... let's merge!

**Comment by ntoll** [comment]
:tada:

**Pull request merged**
