### PR TITLE
Fixed Pyodide transform w/ LiteralMap

### PR DESCRIPTION
**Pull request by WebReflection**
This MR fixes https://github.com/holoviz/panel/issues/7015 by understanding not just *PyProxy* but also the recently introduced [LiteralMap](https://github.com/WebReflection/literal-map#readme) that might be passed along 3rd party modules or code that does explicit conversion.

As those proxies cannot survive *postMessage* dance or serialization in general, they are currently normalized when passed from the worker to the main thread so that errors related to that special `[object Map]` is gone.

I took the opportunity to also relax *coincident* warnings on *deadlock* when it's just main/worker channel being slow (a lot with current panel example).

This has been tested in PyScript already but it needs to land before so I can update the version.

/cc @ntoll @philippjfr @MarcSkovMadsen

### CODE REVIEW

**Comment by WebReflection** [comment]
Actually ... I am going to just publish this as the current state is pretty broken due this regression.

**Comment by philippjfr** [comment]
Amazing, thanks for tracking this down so quickly!

**Comment by WebReflection** [comment]
@philippjfr the real "*hero*" here has bene @MarcSkovMadsen giving me tons of details to play around and reproduce ... your "*so quickly*" was "*eternal hellish time*" to me though 🤣 but I am super happy I've found the culprit. I can't even blame *Pyodide* because we asked for that *LiteralMap* magic to happen, I just forgot that indeed it's yet another Proxy to deal with and now that's hopefully done right.

**Comment by MarcSkovMadsen** [comment]
Great work. Thx.

**Pull request merged**
