### PR TITLE
Added lazy_py_modules

### PR DESCRIPTION
**Pull request by WebReflection**
This MR would like to enable/allow our users to eventually lazily load modules as opposite of having these pre-fetched and already available via the config.

It exposes a `polyscript.lazy_py_modules(...packages)` callback that's going to be awaited so that modules can land on the current session lazily, as opposite of on bootstrap.

The idea is to forward this to the terminal or any other PyScript related session so that an asnc method could always lazily load a module avoiding slow bootstrap when a module is needed only in certain occasions.

I don't know if this is desirable but we already had some user asking for this, and internally neither Pyodide nor MicroPython allow to reach the `loadModule` or `pyimport` internally, for what I could test, so this uses the exposed JS API so that modules can land later on.

please **see the test file attached**

/cc @ntoll @JeffersGlass

### CODE REVIEW

**Comment by JeffersGlass** [comment]
Nice! Just to be clear - from reading the changes, this is about JS Modules (esm), not Python modules, yes?

**Comment by WebReflection** [comment]
@JeffersGlass I am not sure where you comment ended up (email only or removed) but this is about loading *Python* modules within the running interpreter, otherwise not possible as from *Python* code, if I am not mistaken, there's no way to otherwise lazy load from the network or Pyodide wheels modules outside the static, pre-defined, *config.toml* or *.json* ... I hope this is clear and it answered your question.

**Review by ntoll — APPROVED** [review]
I don't see @JeffersGlass's question that you reference @WebReflection. :-/ I assume you've answered to Jeff's satisfaction.

This looks like a good first step because:

1. It's a small change.
2. It works with both MicroPython and Pyodide.
3. You have to be explicit when using it (i.e. default behaviour of PyScript doesn't change).

Next steps (if required):

1. Lazy loading of JS modules in a similar fashion.
2. Lazy loading of our built-in PyScript "stuff" `pydom` and `pyweb` spring to mind.

We should ensure this is documented too. :+1:

**Comment by WebReflection** [comment]
@ntoll about this:

> Lazy loading of JS modules in a similar fashion.

to be honest, JS modules in workers are already lazy loaded, the dance is made synchronous by the implementation, like everything else is in workers, but on top of that, `import js; await js.import("module")` is already possible ... maybe we can just avoid `import` name error and provide a `lazy_js_modules` too for symmetry? The gotcha there is that JS modules usually are better off on the main thread, which is why we have this disambiguation between `js_modules.main` and `js_modules.worker` so we need to be careful in what we expose/offer that, as the Python code never needs such disambiguation.

For `pydom` or `pyweb` we can indeed start simple here and maybe automatically orchestrate a CDN download from our own repository when any of these two names is required, bypassing `micropip` or `mpip` out of the box? maybe @fpliger has other ideas? The fact these are async might not be as straight forward as story for those modules, we need to better think if we just want special treatment via config directly ...

**Comment by WebReflection** [comment]
btw ... 

> We should ensure this is documented too. 👍

good point, I was thinking this should be documented in PyScript once it lands but it's actually a Polyscript feature worth documenting in here too ... I will do if I have time, and before merging it.

**Comment by WebReflection** [comment]
I've added minimal docs around `lazy_py_modules` + an example on how it works.

**Pull request merged**
